# Main page title
title: "Igor Kowalczyk (MAJO)"

# Your name (or nickname/company name)
name: "Igor Kowalczyk"

# Work section title
section: "Portfolio"

# Your job
work: "Front-End Developer"

# Contact E-Mail (Public!)
email: "xxmajonezxx@gmail.com"

# Link to blog - if you don't have - leave blank
blog: "/blog"
# Title of the blog (displays in nav) eg. Blog
blog-title: "Blog"

# Description
description: "Igor Kowalczyk personal website."

# Base url (Not link! Only dir eg. /blog | /portfolio, if you host in the main site - leave blank)
baseurl: ""

# Link to the page (or subpage)
url: "https://igorkowalczyk.github.io"

# Github username (no link) - if you don't have - leave blank
github_username:  "igorkowalczyk"

# First Launch of the site (displays in footer)
first-launch: "2019"

# Timezone
timezone: "Europe/Warsaw"

# Encoding (default: utf-8)
encoding: utf-8

# Markdown and Default theme
markdown: kramdown
theme: minima

# Exlude files/folder (see "/lib/szkola/readme.md")
exclude:
 - Gemfile
 - Gemfile.lock
 - lib/szkola

# Tracking id - if you don't have - leave blank
tracking_id: "UA-153609882-1"

# Verification ID - if you don't have - leave blank
verification: "-wuCsk4qLolXEPSUTGX7YBxywcyNNf5HS2ClzgEWxNY"