# Main Page Title
title: "Igor Kowalczyk"

# Your name
name: "Igor Kowalczyk"

# Main section title
section: "Portfolio"

# Your job
work: "Front-End Developer"

# Section E-Mail link or anchor
section-email: "#contact"

# Description
description: "Igor Kowalczyk personal website."

# Base url (Only dir eg. /blog | /portfolio)
baseurl: ""

# Link to the main page (or subpage)
url: "https://igorkowalczyk.github.io"

# Contact E-Mail
email: "xxmajonezxx@gmail.com"

# Arc.io key
arc: "S9mepABR"

social-media:
 enabled: "true"
 twitter: "@majonezexe"
 github_username: "igorkowalczyk"
 discord: "https://discord.gg/bVNNHuQ"
 instagram: majonezexe
 wattpad: "majonezexe"
 # facebook: igor-kowalczyk.0000 / 51144145433434332

 projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
   archived: false
   forks: true
   projects:
   # - repo-name

# Display svg decorations (boolean)
cards:
 enabled: "true"

# Extra link on navigation
blog: "/blog"

# Title of the extra link
blog-title: "Blog"

# Support to mobile browsers (It’s unknown what range of browsers support this meta tags) [Better to set the value to "false"!] (Boolean)
mobile: "false"

# First Launch of the site
first-launch: "2019"

# Timezone
timezone: "Europe/Warsaw"

# Encoding (default: utf-8)
encoding: utf-8

# Markdown and Default theme
markdown: kramdown
theme: minima

# Exlude files/folder
exclude:
 - Gemfile
 - Gemfile.lock

# Contact form
form:
 enabled: "true" # Display form on page (boolean)
 disabled: "true" # Disable the contact form inputs but don't hide the whole form. Enable this for eg. maintenance. (boolean)
 hide_html_form: "true" # Hide HTML form from page
 action: "https://getform.io/f/f823ef85-b161-4cc1-9d60-ef2fb18b9276" # Form action, must support xhr requests (url)
 banner: "https://discord.c99.nl/widget/theme-4/544164729354977282.png" # Form banner (url)
 banner_url: "https://discord.com/users/544164729354977282" # Banner url (url)
 display_banner: "true" # Display form banner (boolean)

# Google Tracking ID
tracking_id: "G-629JN1JKVT"

# Google Site Verification ID
verification: "-wuCsk4qLolXEPSUTGX7YBxywcyNNf5HS2ClzgEWxNY"

# Coding stats
wakatime:
 enabled: "true" # Boolean
 started: "2021" # Year when wakatime started moritoring your code activity
 link: "https://wakatime.com/@Majonezexe" # Your wakatime profile link
 embed: "https://wakatime.com/share/@Majonezexe/6649e5e0-8191-4da7-b51c-8ef035b7e069.svg" # Coding stats embed image in .svg format

 plugins:
  - jekyll-github-metadata
