name: Jekyll Deploy

on:
 push:
  branches: [master]
 schedule:
  - cron: "0 * * * *"

jobs:
  build:
  name: ✨ Jekyll build
  runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
