name: Prettier format

on:
 workflow_dispatch:

jobs:
 install:
  name: Install Prettier
  runs-on: ubuntu-latest
  strategy:
   fail-fast: false
   matrix:
    language: ["javascript"]
    node: ["16.x"]
  steps:
   - name: 🧱 Checkout repository
     uses: actions/checkout@v2
   - name: 🚀 Install dependencies
     run: npm i prettier@2.6.2 --no-package-lock --legacy-peer-deps
 format: 
  name: Format
  needs: [install]
  runs-on: ubuntu-latest
  strategy:
   fail-fast: false
   matrix:
    language: ["javascript"]
    node: ["16.x"]
  steps:
   - name: 🧱 Format code
     run: "cd ${{ github.workspace }} && npm run format"
 commit:
  name: Commit
  runs-on: ubuntu-latest
  needs: [format]
  strategy:
   fail-fast: false
   matrix:
    language: ["javascript"]
    node: ["16.x"]
  steps:
   - name: "🚀 Commit formatted code"
   - uses: stefanzweifel/git-auto-commit-action@v4
    - with:
     commit_message: "[🚀] Code formatting"
     branch: ${{ github.head_ref }}
     commit_user_name: IgorKowalczykBot
     commit_user_email:
