name: Prettier check

on:
 push:
  branches: [master]
 pull_request:
  branches: [master]

jobs:
 check:
  name: Analyze
  runs-on: ubuntu-latest
  strategy:
   fail-fast: false
   matrix:
    language: ["javascript"]
steps:
 - name: 🧱 Checkout repository
   uses: actions/checkout@v2

 - name: 🚀 Install dependencies
   run: npm i prettier@2.6.2 --no-package-lock --legacy-peer-deps
   with:
    languages: ${{ matrix.language }}

 - name: 🚀 Check formatting
   run: "npm run format"
