name: Jekyll Deploy

on:
 schedule:
  - cron: "0 * * * *"
 push:
  branches: [master]

jobs:
 build:
  name: ✨ Jekyll build
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - uses: helaili/jekyll-action@v2
     with:
      token: ${{ secrets.GITHUB_TOKEN }}
      target_branch: "gh-pages"
